### ISSUE TITLE
npm-package difficult to import due to package-name ending with .js

### ISSUE THREAD

**Issue by erhuz** [davideperozzi/momentum-js#10]
Node thinks momentum.js is a file in the same directory as file which tries to import momentum.js. Might differ between Node-versions. But Node `v11.13.0` is not compatible.

**Comment by davideperozzi** [comment]
Have you tried to import it like this: `import 'momentum.js/dist/momentum.min.js'`.
If you're using webpack you could try it using the `exports-loader` like this
`import momentum from 'exports-loader?momentum!momentum.js/dist/momentum.min.js'`

**Comment by erhuz** [comment]
Thanks for your fast reply! `import 'momentum.js/dist/momentum.min.js` worked fine, but is kind of misleading at first. You should add it to the documentation in your README.md file.
