### ISSUE TITLE
Loading momentum.js via parcel returns empty object

### ISSUE THREAD

**Issue by nileshinkane** [davideperozzi/momentum-js#11]
Here is what I did

```
import { Tween } from "gsap/gsap-core";
import momentum from "momentum.js/dist/momentum.min.js";

const animateHeroImages = () => {
   // Some random function
};

const draggable = () => {
  const cloud = document.querySelector(".cloud");
  const container = document.querySelector(".hero-container");
  console.log(cloud, container);

  let drag = new momentum.Draggable(cloud, {
    container: container,
    friction: 0.055,
    containerBounds: true,
    resizeUpdate: true,
    autoAnchor: true,
  });
  console.log(momentum);
};

export { animateHeroImages, draggable };

```

This gives me console error -

**indexScripts.js:42 Uncaught (in promise) TypeError: _momentumMin.default.Draggable is not a constructor.**

Also when I console log the imported momentum from the dist folder, it returns an empty object.

I am using - 
1) Chrome - 83
2) [parcel-bundler](https://parceljs.org/)

**Comment by davideperozzi** [comment]
Hi @nileshinkane 

Try updating to version `1.2.2`. With that version you are able to use normal imports:

```js
import { Draggable } from "momentum.js";
``` 
Parcel should handle the rest :)
